# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed6624ec822b40c19feb58a63440a758cce2a04aaef43d28f11029c4203cf4c245b7f9c4d94a90111e6d905f18d6432a1414538f116b15062b54b144c6e64816

test:
  secret_key_base: 66e37dc0293a01348c8826c1f0f84a2f0e9edf4a21edceccb73d4554ff37d30b9bd3136b048a3e738b65b19b3c3894c6e462d3fbf86263bd79fdea73e150d8b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
